name: Deploy Maven Package

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  
        distribution: 'temurin'  
        cache: maven


    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Import GPG Key
      env:
        GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
        GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
      run: |
        echo "$GPG_SECRET_KEYS" | gpg --batch --import
        echo "$GPG_OWNERTRUST" | gpg --batch --import-ownertrust

    - name: Publish to Maven Central
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
       mvn -U -B clean deploy -P release


