name: Deploy Maven Package

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  
        distribution: 'temurin'  
        cache: maven


    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Configure GPG
      run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --pinentry-mode loopback --quick-set-expire $(gpg --list-keys --with-colons | grep pub | cut -d':' -f5) 0

    - name: Publish to Maven Central
      env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: mvn deploy -P release --batch-mode -DskipTests


